// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4qcWghKgrJoW9muEvIqu3UqOWzMIyNwQ',
    appId: '1:349698588987:web:e2ade70f9cf394c7f7f71e',
    messagingSenderId: '349698588987',
    projectId: 'fir-chatapp-7b6c7',
    authDomain: 'fir-chatapp-7b6c7.firebaseapp.com',
    storageBucket: 'fir-chatapp-7b6c7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpNYEe7LWd5S846Y4XRCdMsLjPqJJqB9g',
    appId: '1:349698588987:android:bc09f080cf977801f7f71e',
    messagingSenderId: '349698588987',
    projectId: 'fir-chatapp-7b6c7',
    storageBucket: 'fir-chatapp-7b6c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDauIavm7ExWzNJo6TX4xFgti8Zodlz26Q',
    appId: '1:349698588987:ios:bb06127846c9229ff7f71e',
    messagingSenderId: '349698588987',
    projectId: 'fir-chatapp-7b6c7',
    storageBucket: 'fir-chatapp-7b6c7.firebasestorage.app',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDauIavm7ExWzNJo6TX4xFgti8Zodlz26Q',
    appId: '1:349698588987:ios:bb06127846c9229ff7f71e',
    messagingSenderId: '349698588987',
    projectId: 'fir-chatapp-7b6c7',
    storageBucket: 'fir-chatapp-7b6c7.firebasestorage.app',
    iosBundleId: 'com.example.firebaseChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4qcWghKgrJoW9muEvIqu3UqOWzMIyNwQ',
    appId: '1:349698588987:web:74fffc2933606fbdf7f71e',
    messagingSenderId: '349698588987',
    projectId: 'fir-chatapp-7b6c7',
    authDomain: 'fir-chatapp-7b6c7.firebaseapp.com',
    storageBucket: 'fir-chatapp-7b6c7.firebasestorage.app',
  );
}
